# Generated by Django 3.1.1 on 2020-09-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200920_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
