# Generated by Django 3.1.1 on 2020-10-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='validated',
        ),
        migrations.AddField(
            model_name='certification',
            name='tracking',
            field=models.BooleanField(default=True),
        ),
    ]
